// Generates src/styles/tokens.css from the design tokens (tokens.json is the source of truth).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = JSON.parse(readFileSync(resolve(root, '../design/tokens/tokens.json'), 'utf8'));

const vars = (theme) =>
  src.color.tokens.map((t) => `  --${t.name}: ${t.value[theme]};`).join('\n');

const css = `/* Generated by scripts/gen-tokens.mjs from design/tokens/tokens.json. Do not edit. */
:root, :root[data-theme='dark'] {
${vars('dark')}
}
:root[data-theme='light'] {
${vars('light')}
}
@media (prefers-color-scheme: light) {
  :root:not([data-theme]) {
${vars('light')
  .split('\n')
  .map((l) => '  ' + l)
  .join('\n')}
  }
}
`;

mkdirSync(resolve(root, 'src/styles'), { recursive: true });
writeFileSync(resolve(root, 'src/styles/tokens.css'), css);
console.log(`tokens.css: ${src.color.tokens.length} colors`);
